print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")
print("adil")
print("azmain adil")